sudo: required
dist: trusty

language: c

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
    packages:
      - libcunit1
      - libcunit1-dev
      - tup
      - valgrind

script:
  - tup
