sudo: required
dist: trusty

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
    packages:
      - libcunit1-dev
      - tup

script:
  - tup
